### ISSUE TITLE
Basin summary plots

### ISSUE THREAD

**Issue by a753bart** [rcapell/HYPEtools#46]
It would be great to have a function to plot water quality related charts. Here is my recommendation for the plots. I kind of put together an example of what it should look like in the enclosed Word document using some of the old mismatched charts I had. the WQ part would get repeated for all constituents present or selected – IN, ON, TN, IN/TN, SP, PP, TP, SP/TP. The only thing that is not displayed there is the range we talked about for the seasonality plots. The simple plots there have 2 lines; the plots we would want to have would be little more complex. Observed values would be shown as whisker&box plots with means and medians connected by a line. Simulated values would be represented also by the mean and median lines but also a shaded range present for each month. Ideally, this would be in two different shades: darker for values between 25th and 75th percentiles and lighter shade for values from minimum to 25th perc. and 75th perc. to maximum. I enclosed my highly artistic finger-painted version below. The range would be calculated for the month, so it would be more box-like in reality than what I drew. Red is simulated, black observed in the drawing. 

[WQ_plots_sketch.docx](https://github.com/rcapell/HYPEtools/files/349656/WQ_plots_sketch.docx)
![wq_seasonal_plot_sketch](https://cloud.githubusercontent.com/assets/20319028/16617246/ee9804da-4382-11e6-90ad-bc05c1a9b26d.png)

**Comment by rcapell** [comment]
thanks for the suggestion, I will write a comment here as soon as a first version of this is ready for testing.

Any naming suggestions? The basic time series plot is called PlotBasinOutput(), which is maybe a bit unfortunate because this one will also be based on basinoutput files. On the other hand, PlotBasinOutput() is really close to the actual data contained, while the plots here are more derived.
Maybe PlotBasinWq() or PlotBasinNutrients()?

**Comment by a753bart** [comment]
What about PlotBasinSummary()? It does plot summarized information for both Q and WQ, maybe the WQ does not need to be specified in the title

**Comment by rcapell** [comment]
PlotBasinSummary() implemented, _needs testing_. See attached plot for how it looks like at the moment.

One note: 
The function can be quite slow for sub-basins with many upstream sub-basins. This because it takes time to compute all the upstream aggregation for the bar plots in the first row. It would be more efficient for repeated plotting if the function could deal with pre-computed upstream aggregates, but for the moment the current version has to do.

![plot_basin](https://cloud.githubusercontent.com/assets/6536193/18208361/85425eec-712f-11e6-8893-8272b0793805.png)

**Comment by a753bart** [comment]
It would be great if you can add an option to plot concentrations and flows on a log scale.
Also, make the top row of plots optional to speed up the script for larger number of sites.

**Comment by rcapell** [comment]
Ok! 
Do you want:

(a) this to be applied on all panels?
(b )the log scaling to be the default option?

**Comment by a753bart** [comment]
(a) Yes! Where concentrations or flows are on any axis. Ratios, probabilities, months should stay the same.
(b) Either way. It's not hard to add another parameter so whatever works with the overall vision. I think most of the plots have default arithmetic scale so it would be good to stick with the same.
Thanks!

**Comment by rcapell** [comment]
New arguments "panels", which allows to include/exclude bar charts, "log" for log-scaling, "xscale" for scaling of duration curve x-axes.

Please close this issue if the function is good enough for now.

**Comment by a753bart** [comment]
It seems to be working pretty well now! It would be nice if the name could also be plotted for panels option 2 but that is rather minor. Thanks for the plot function, looks really great!
