### ISSUE TITLE
PlotMapOutput does not handle NA in data with "ColDiffGeneric"

### ISSUE THREAD

**Issue by a753bart** [rcapell/HYPEtools#71]
I'm getting this error when plotting using PlotMapOutput with color ramp set to "ColDiffGeneric" and the data contain NA

> png(paste0(srcdir, out.dir, prfix, "plot_map_month_mean_",varlst[ii], "_", rcp.fnm[k1], "-",rcp.fnm[k2],"_diff_BSB.png"), res = 600, units = "cm", width = 23, height = 20)
>  PlotMapOutput(map.month.mean.diff, mapsbd_balt, map.subid.column = 1, varlst[ii], col.ramp.fun = "ColDiffGeneric", 
+     par.mar = c(0,0,0,7)+.1, legend.inset = -.11, legend.title = paste0("Mean ",varlst[ii],", ", varunitlst[ii]),plot.scale = F)
[SCN_map_month_mean_ref-refssp1luse_CCTN_diff_BSB.txt](https://github.com/rcapell/HYPEtools/files/999220/SCN_map_month_mean_ref-refssp1luse_CCTN_diff_BSB.txt)

Error in seq.default(0, log(max(abs(range(x[, 2]))) + 1), length.out = 5) : 
  'to' cannot be NA, NaN or infinite
> dev.off()

**Comment by rcapell** [comment]
The problem is probably with your data file. I get a factor in column two, not a numeric. 

If you use ReadMapOutput for import, it expects a two-row header. First line with a comment, and second with column headers.

Also, your data file has a combined comma-space separator, which is a bit unusual and not handled by ReadMapOutput. "te3" in example code below is a working import command for your file (I did not test the plot function because I don't have the mapsbd_balt shape file here, but it probably will work).

```R
te3 <- read.csv("../SCN_map_month_mean_ref-refssp1luse_CCTN_diff_BSB.txt", header = T, sep = ",", strip.white = T)
x11()
PlotMapOutput(te3, mapsbd_balt, map.subid.column = 1, varlst[ii], col.ramp.fun = "ColDiffGeneric",
              par.mar = c(0,0,0,7)+.1, legend.inset = -.11, legend.title = paste0("Mean ",varlst[ii],", ", varunitlst[ii]),plot.scale = F)
dev.off()
```
