### ISSUE TITLE
DirectUpstreamSubids returns list, not vector as described in help

### ISSUE THREAD

**Issue by rcapell** [rcapell/HYPEtools#79]
observed when run with subid of headwater (no upstream subids) and get.weights = F

**Comment by c-brendel** [comment]
I'm pretty sure this issue is actually referring to the AllUpstreamSubids() function instead of the DirectUpstreamSubids() function. I tested AllUpstreamSubids() with a headwater subbasin as described above, and it correctly exports a vector.

**Comment by c-brendel** [comment]
AllUpstreamSubids() doesn't seem to work if get.weights = TRUE (both with headwater and non-headwater subbasins). Error message:
Error in if (this.sub - floor(this.sub) > 0) { : 
missing value where TRUE/FALSE needed

I think the problem is that the findfun.gw() helper function is returning a vector with a bunch of NA values
