### ISSUE TITLE
Update PlotBasinSummary and PlotBasinOutput to handle new parameters

### ISSUE THREAD

**Issue by a753bart** [rcapell/HYPEtools#83]
Sediment would have a priority for me but other constituents such as pathogens should be included also if possible.

**Comment by a753bart** [comment]
It seems that only reSS&ccSS are implemented. We also need reTS and ccTS. 

Would be great to have loads too but we don't have a unique name for observed loads.

**Comment by rcapell** [comment]
- Added TS, T1, and T2 (T2 only in PlotBasinOutput) to the functions. 
- The functions will now per default plot to a pdf file device.
- The 'hype.vars' argument value "nutrients" is now called "wq", because there are also sediment and tracer to be plotted.
- Plus some auditing of Jude's additions.

@a753bart: Regarding loads. I think observations are now available as distinct variables (rlIN, rlON, ...). None added yet, would all panels we use for concentrations make sense with loads?
