### ISSUE TITLE
NetCDF preprocessing

### ISSUE THREAD

**Issue by goord** [rcapell/HYPEtools#91]
Hi, I was wondering whether it would be possible to create HYPE input meteo files, i.e. ```ForcKey.txt```, ```Pobs.txt```, ```Tobs.txt```, etc. from a netcdf input file on a rectangular gaussian grid and the subbasin shape file of the model. I believe there is this functionality within WHIST, but is there also a command line tool?

**Comment by LennartSchoenfelder** [comment]
Hei,

I don't usually git hub so much, but I have different R scripts to do that task.
The attached one has a lot of comments and you might have to edit a lot depending on your ncdf file.

[Tobs prep fro NETCDF.txt](https://github.com/rcapell/HYPEtools/files/3779157/Tobs.prep.fro.NETCDF.txt)

**Comment by dgustafsson** [comment]
Hi, I recently developed a set of tools to create HYPE meteo files from the HydroGFD netcdf files that you might want to check as well. The script from Lennart is more to the point,  but I guess my tools does something similar.  

It assumes netcdf dimension lat, lon, time, and the netcdf variable name provided by the user.

It takes the intersection of grid cells and subbasin polygons to assign weights to each gridcell (a common approach at SMHI has otherwise been to take the nearest gridcell). To do this you first have to build a polygon layer representing the grid cells (a function is included) - maybe it is a bit clumpsy method. Building a raster would probably do the same trick. The weights and grid cell information is saved as a list array for re-use for additional files.

Attached is a file with "utils" with an example section that is hidden by an if-statetment. And a file with an example application. 

[netcdf_to_obs.zip](https://github.com/rcapell/HYPEtools/files/3797340/netcdf_to_obs.zip)

I am also about to write some function to import/export HYPE output files in netcdf format. I guess it will be added to HYPEtools at some point when we have agreed on the data model. /David

**Comment by rcapell** [comment]
Given that this issue has been open and unaddressed for a long time now, I can comment that we (SMHI) do this preprocessing as part of a different workflow, and I don't see this being imlemented by me any time soon. 

Contributions in form of function (drafts) are welcome though, the functionality would definitely fall within the scope of HYPEtools.

Closing for now.

Regarding @dgustafsson 's last point on import/export of HYPE output files in netcdf, we now have a separate issue #117 for that.
